deepcell_toolbox/utils.py, deepcell_toolbox/utils_test.py
The current implementation of resize uses linear interpolation. This works fine for image data, but for labeled images this will average adjacent labels. I added in a data_type keyword argument to control this behavior, as well as logic to perform nearest-neighbor interpolation for labeled images.
=> Maintain integer values when resizing labels

deepcell_toolbox/deep_watershed.py
The `deep_watershed` post-processing function selects the `fgbg` layer out of the model response, but it is never used. By removing this, the list does not need to contain the fgbg results at all, and post-processing will remain intact.
=> Remove the reference to fgbg output in deep_watershed.

deepcell_toolbox/metrics_test.py, deepcell_toolbox/utils.py, deepcell_toolbox/utils_test.py
Fixes #13 
Fixes #12 
This PR removes the `dtype` option for `untile_image` and instead will preserve the `dtype` of the input data `tiles`.
Additionally, this PR adds several tests for `tile_image` and `untile_image` to test different combinations of input shape, model shape, dtype, and stride ratio. In building these tests, a couple of bugs were found in both functions:
* Using `int(np.ceil(x / y))` instead of `int(x / y)` leads to deterministic indices. there were issues with smaller values of `stride_ratio`.
* `untile_image` was checking the x-axis for its terminus point instead of the y-axis, causing problems with some rectangular images.
* Raise `ValueError` if input image to `tile_image` is not 4. (Fixes #12)
=> Fix bugs in tile_image and untile_image

deepcell_toolbox/utils.py, deepcell_toolbox/utils_test.py, requirements.txt
Swap the target axes if using `cv2` for resizing images to get the output shape to have the proper x and y axes.
=> CV2 expects swapped axes in resize target shape.

.gitignore, .travis.yml, deepcell_toolbox/__init__.py, deepcell_toolbox/compute_overlap.pyx, deepcell_toolbox/compute_overlap_3D.pyx, deepcell_toolbox/metrics.py, deepcell_toolbox/retinanet.py, pytest.ini, requirements.txt, setup.py
Fixes #38 by removing the dependency on `keras-retinanet` and take the `compute_overlap` function out and using it directly.
=> Replace keras-retinanet with compute_overlap.pyx

deepcell_toolbox/utils_test.py
Because the tests are using random data, sometimes the eroded edges are both 0, so we can edit the comparison to be `>=` insetad of just `>`.
Fixes #25
=> Fix erode_edges 3D tests.

.travis.yml, deepcell_toolbox/deep_watershed.py, deepcell_toolbox/deep_watershed_test.py
This PR brings in the new functionality vanvalenlab/deepcell-tf#413 for better formatting of model output, and also adapts the existing post-processing functions to handle it. 
- Add format_output_multiplex() to take the list of model outputs, and convert them into a nicely structured dict
- Add deep_watershed_subcellular() to take the formatted model output, and pass either the nuclear predictions, the whole-cell predictions, or both, to deep_watershed_mibi()
- Change deep_watershed_mibi() to expect a dictionary of model outputs, rather than a list
- Pull out additional hard-coded parameters in deep_watershed_mibi and add them as default function arguments to enable them to be changed if desired
- Wrap all of these in a kwargs dict and hide them in high-level functions
=> reformatted multiplex postprocessing

deepcell_toolbox/processing.py, deepcell_toolbox/processing_test.py
- `normalize` and `pixelwise` expect batch axes (Fixes #21)
- `pixelwise` adds `interior_axis` (defaults to -2) to make it more flexible (Fixes #20)
=> All processing functions expect a batch dimension

deepcell_toolbox/utils.py, deepcell_toolbox/utils_test.py
This PR has two main changes. The first is to substitute the for loop that erodes each cell individually with the built-in python function find_boundaries. 
The second is to modify the tests for erode_edges_3D to assert that each erosion generates a progressively smaller image. The reason the current tests were failing is because with some frequency, erode_edges_3d would erode the entire image with an erosion_width of 1. This means that the erosion_width 2 image would also be blank, and the assert would fail. 
I modified the test data so that each cell is, on average, larger than it was before, and thus the chances of having all cells completely eroded with an erosion_width of only 1 is unlikely. 
However, it worries me that this issue never cropped up for the 2D data. The radius of the …
=> Improvements to erode_edges

deepcell_toolbox/deep_watershed.py, deepcell_toolbox/deep_watershed_test.py, deepcell_toolbox/utils.py, deepcell_toolbox/utils_test.py
This PR updates the multiplex postprocessing function
- Switches from peak_local_max to h_maxima, which Dave found does a better job at detecting maxima in images
- Adds the option for a pixel expansion to do nuclear-based segmentation
One thing that I wanted to include was a fill_holes option. The remove_small_objects setting will remove small objects from the image. However, for the current multiplex model, these small objects are usually located within another label. So what we'd like to do is remove them, and then change those pixels back to the value of the label they are within. 
However, I couldn't seem to find a function that does this. Do you know of anything that would accomplish this? [skimage.remove_small_holes ](https://scikit-image.org/docs/dev/api/skimage.morphology.html#ski …
=> tweaked watershed params

deepcell_toolbox/metrics.py, deepcell_toolbox/metrics_test.py
Metrics currently assumes all images have at least one pixel of background. For images with dense cells and no background, the number of cells is not computed correctly, leading to an indexing error. Closes #53
=> Fix dense labels bug in Metrics

.travis.yml, requirements-test.txt
- Add a requirements-test.txt for managing test dependencies.
- Use `--upgrade` when installing testing requirements to fix #57
=> Update testing requirements for python 3.5 compatibility.

deepcell_toolbox/processing.py, deepcell_toolbox/processing_test.py
This PR adds a function, `percentile_threshold`, which thresholds signal in an image above a given percentile. This is useful for very bright signal to bright it back down to the same regime of the rest of the image. 
In addition, because the applications currently only support passing 1 preprocessing function, I created a new preprocessing function, `multiplex_preprocess`, which combines thresholding with histogram normalization
=> Thresholding of bright image signal

deepcell_toolbox/processing.py, deepcell_toolbox/processing_test.py
The `percentile_threshold` function currently fails if a completely blank image is supplied. This PR closes #66 by adding a check for completely blank images, and skipping thresholding if so.
=> Handle blank images in preprocessing

deepcell_toolbox/processing.py, deepcell_toolbox/processing_test.py
`processing.normalize` divides the image's mean value by its standard deviation. This PR adds a very small `epsilon` to the standard deviation to prevent any `NaN` issues when the standard deviation is 0.
A default value of `1e-07` is used as that is the default value found in `keras.backend.epsilon()`.
Fixes #71
=> Add epsilon to normalize computation to prevent zero division.

deepcell_toolbox/utils.py
Instead of only tiling inputs with zero-padding, the `pad_mode` allows for any valid numpy padding mode, including `reflect`.
Additionally, updates the validation error message to close #80
=> Add new `pad_mode` argument to `tile_image` to override padding mode.

deepcell_toolbox/retinanet_test.py
The scores are randomly generated in the test data, so it is possible that the scores are all below the `score_threshold`. This PR sets a single score to .999 for each batch in the tests, forcing the score to be above the threshold.
=> Set a high score in every batch for in RetinaNet tests

deepcell_toolbox/retinanet.py
The following line could result in all values of the array being `-1`, which is an invalid dimension for a numpy array.
```python
segments = random_walker(foreground, markers)
```
This PR specifically checks if all of the segments are -1, and skips any invalid behavior. Additionally, move shared code in constructing the masks into a utility helper function, as the dangerous code existed in both `retinamask_postprocess` and `retinamask_semantic_postprocess`.
=> Fix bug in RetinaMask postprocessing that would fail if all masks are invalid.

deepcell_toolbox/metrics.py
We currently don't check that there are valid predictions when computing precision, which can lead to divide by zero errors.
=> Check for divide by zero

deepcell_toolbox/metrics.py, deepcell_toolbox/metrics_test.py
Easier to ask for forgiveness than permission.
Try to do the precision and recall division and just catch the `ZeroDivisionError` if it occurs. There should not be a case where `n_true` is 0, but just in case there is, prevent the crash.
=> Wrap both precision and recall in a try/catch.

deepcell_toolbox/deep_watershed.py
`skimage.morphology.watershed` is deprecated and removed in `skimage` v0.19. This PR uses `skimage.segmentation.watershed` instead, which is supported by at least 0.14+.
This resolves an annoying deprecation warning we get every time we use the post-processing function.
=> Import `watershed` from `skimage.segmentation`.

deepcell_toolbox/deep_watershed.py
The only difference in these two functions was the dimensionality of the `coords` found in `peak_local_max`. Switching to a comprehension allows us to easily use 2D or 3D data with the same function.
`deep_watershed_3D` is now deprecated (and throws a Deprecation Warning), but is kept for now for backward compatibility.
=> Combine `deep_watershed` and `deep_watershed_3D` & deprecate `deep_watershed_3D`.

deepcell_toolbox/deep_watershed.py, deepcell_toolbox/deep_watershed_test.py
This PR combines `deep_watershed` and `deep_watershed_mibi` into a single function, `deep_watershed`.
The following arguments have been deprecated in favor of their `deep_watershed_mibi` alternatives (due to readability/understandability):
- `min_distance` deprecated in favor of `radius`
- `distance_threshold` deprecated in favor of `interior_threshold`
- `detection_threshold` deprecated in favor of `maxima_threshold`
Additionally, new arguments have been moved over from `deep_watershed_mibi`:
- `maxima_smooth` and `interior_smooth` to smooth the inputs with a gaussian filter.
- `fill_holes_threshold` to fill holes smaller than this many pixels
- `pixel_expansion` to expand the `interior` array
- `maxima_algorithm` to switch from `h_maxima` peak finder to `peak_local_max`. By default, …
=> Combine `deep_watershed` and `deep_watershed_mibi`

.github/workflows/tests.yaml, deepcell_toolbox/metrics.py, pytest.ini
Precision and SEG were being multiplied by 100 while Recall was not. This removes the 100x casting to make all metrics be in the same range [0, 1].
Additionally, fixes the `norecursedirs` value in `pytest.ini` to be space-delimited instead of comma-delimited.
Finally, pins `coveralls<3.3.0` to prevent a breaking change in the latest release.
Fixes #117
=> Set Recall, Precision, and SEG to all have same scale.

.github/workflows/deploy.yaml
numpy restriction for the toolbox requires Python < 3.10
=> Pin python-version to 3.8 for PyPI deployment.

.github/workflows/tests.yaml, pytest.ini, setup.py
Adds support for Python 3.10. No changes to the underlying library but some dependency updates were required, the main ones being:
- removing the upper-bound on `pytest`, and
- Dropping the `pytest-pep8` extension, which [hasn't been actively maintained in over 8 years](https://pypi.org/project/pytest-pep8/#history)
We can of course re-add code linting using different tooling - I'm happy to do so but would prefer to leave it for a follow-up PR.
=> Add Python3.10 support

deepcell_toolbox/__version__.py, deepcell_toolbox/deep_watershed.py, deepcell_toolbox/deep_watershed_test.py, deepcell_toolbox/metrics.py, deepcell_toolbox/metrics_test.py, deepcell_toolbox/processing.py, deepcell_toolbox/utils.py, pytest.ini
The current pytest configuration is [suppressing all deprecation warnings](https://github.com/vanvalenlab/deepcell-toolbox/blob/fd398ebf1b21e313870aed745413503dacfb29f2/pytest.ini#L6-L9), which includes warnings from dependency libraries. This makes it much more likely for code to fall out-of-date, as can be seen in [the recent failing CI jobs](https://github.com/vanvalenlab/deepcell-toolbox/actions/runs/3734920418/jobs/6337547681) due to changes in the lastest version of numpy which was just releases (1.24).
This PR addresses the issue in two ways:
1. Updates code to take into account changes in the underlying libraries, and
2. Removes the global warnings filter in favor of fine-grained warnings filtering.
The second bullet involves adding explicit checks for warnings raised by …
=> MAINT: update deprecated code from dependencies and remove warnings filters

.github/workflows/deploy.yaml, .github/workflows/tests.yaml
Bump action versions to keep CI current, c.f. https://github.com/vanvalenlab/deepcell-tf/pull/653
=> Bump default action versions.
